### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TOWUK** [ploi-deploy/roadmap#100]
1 )ordinary users can create items visible only to them and the administrator when it is forbidden to do this (except for those projects in which it is allowed to create items on the boards)![image](https://user-images.githubusercontent.com/28830162/175076854-373451b6-a91b-4ecc-a7ee-d64c18f8f59f.png)
![image](https://user-images.githubusercontent.com/28830162/175076993-a424d363-e842-4f5d-b93d-c799f07d4dd8.png)

2) how to expand whiteboard window? this is not very convenient on large screens where the resolution is 1080p
![image](https://user-images.githubusercontent.com/28830162/175077768-01e749dd-d01a-4776-a1ab-f4f4299c2d6e.png)

**Comment by Cannonb4ll** [comment]
Hi,

I don't really understand point 1, but if you want feel free to submit a fix for point 2 and elaborate point 1 a bit differently.

**Comment by TOWUK** [comment]
> Hi,
> 
> I don't really understand point 1, but if you want feel free to submit a fix for point 2 and elaborate point 1 a bit differently.

in the settings it is forbidden for USERS to create items, but they can do it, since there is a button for this, even if they do this, no one sees their items, except for their profile and administrator logs, I would like more rights settings for each role, for example, that you can create and what is not possible / will not show the button, about the second item, a very small interface, the window is small, the floor of the screen is just empty and the bottom too!

**Comment by TOWUK** [comment]
> Hi,
> 
> I don't really understand point 1, but if you want feel free to submit a fix for point 2 and elaborate point 1 a bit differently.

the scroll fields are not in the right place, not at the bottom and not on the right, but in the centers of the screen, how to fix it?

**Comment by Cannonb4ll** [comment]
> > Hi,
> 
> > 
> 
> > I don't really understand point 1, but if you want feel free to submit a fix for point 2 and elaborate point 1 a bit differently.
> 
> 
> 
> the scroll fields are not in the right place, not at the bottom and not on the right, but in the centers of the screen, how to fix it?

It's designed like that, feel free to submit a PR with the change how you'd like to see it. This also goes for point 1.

**Comment by Cannonb4ll** [comment]
I'm not liking this vibe your putting out with your demands, exclamation marks and the lack of ability to stay normal and help. I'm closing this for now.
