### ISSUE TITLE
Help with SSO

### ISSUE THREAD

**Issue by FiveMDevv** [ploi-deploy/roadmap#118]
Hi. I am trying to follow the docs on how to set up SSO, and I do not see where I should put my server URL and Client ID and Secret

**Comment by FiveMDevv** [comment]
hi @ndijkstra
I recloned the git repo with no changes of my own

I set those values from my Forum Software and Deployed

I Login and get a 500 error

**Comment by ndijkstra** [comment]
So what does the 500 errors says in your logs?

**Comment by FiveMDevv** [comment]
The only error I see is 

[2022-06-28 13:58:28] local.ERROR: The MAC is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at /home/ploi/feedback.site.com/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:218)

**Comment by ndijkstra** [comment]
It looks like you generated a new APP_KEY then and it is trying to decrypt a value that was encrypted with the old APP_KEY.

**Comment by FiveMDevv** [comment]
Please let me know if you need any more information or how I can get this to work!

**Comment by FiveMDevv** [comment]
@Cannonb4ll Have any idea?

**Comment by Cannonb4ll** [comment]
I don't know what the issue is here, but I feel like this is an issue to ask in the Laravel community rather than here. We've already seen a few people set it up successfully so it shouldn't be too much of a problem to do so.
