### ISSUE TITLE
ability to change the number of items to more then 5 

### ISSUE THREAD

**Issue by Kyzoe** [ploi-deploy/roadmap#131]
in the created items overview you have a dropdown where you can choose how many items you want to see, it is default on 5 but i have 25 and there is no way to choose more then 5. 

i would love to see 10/25/50 or all in the dropdown.

**Comment by Silver343** [comment]
@Cannonb4ll Do you think this should be configurable in the settings with a predefined list?

**Comment by Cannonb4ll** [comment]
@Silver343 I think it would be better to have this user-level configuration. So in their profile under a new settings tab a dropdown or something.
