### ISSUE TITLE
After login redirect to intended page

### ISSUE THREAD

**Issue by ndijkstra** [ploi-deploy/roadmap#134]
After logging in with my credentials you always get redirect to the home of the roadmap. It would be nice to redirect back to the intended page.

**Comment by Cannonb4ll** [comment]
It seems to work for me?

Visit /profile without being logged in, then you get the login form, login, and you'll be redirected to the /profile page.

**Comment by ndijkstra** [comment]
You can reproduce it with these steps:

* Make sure to be not logged in on roadmap.ploi.io
* [https://roadmap.ploi.io/projects/6-api-level-requests/items/64-install-new-php-version-on-server](https://roadmap.ploi.io/projects/6-api-level-requests/items/64-install-new-php-version-on-server)
* Login
* After login you get redirected to https://roadmap.ploi.io/

**Comment by Cannonb4ll** [comment]
> You can reproduce it with these steps:
> 
> 
> 
> * Make sure to be not logged in on roadmap.ploi.io
> 
> * [https://roadmap.ploi.io/projects/6-api-level-requests/items/64-install-new-php-version-on-server](https://roadmap.ploi.io/projects/6-api-level-requests/items/64-install-new-php-version-on-server)
> 
> * Login
> 
> * After login you get redirected to https://roadmap.ploi.io/

Yeah but, how would you know to redirect to that item page after you press the login page? Are you talking about voting and redirecting?

**Comment by ndijkstra** [comment]
Yes, was just thinking about that ':). Never mind!
