### ISSUE TITLE
My Feature Request does not appear on the list

### ISSUE THREAD

**Issue by planetahuevo** [ploi-deploy/roadmap#151]
I just created a new feature, and I can see it on my items, but it does not appear on the board under its category.
I think that because of that, it also gives me an error every time I edit it, but the edit work. 
The error is because after editing, it send me to the list, and the item is not there: 
 
![image](https://user-images.githubusercontent.com/12070380/180596780-1ac1de17-9c26-41f1-8fd7-d5287dbb951f.png)

The steps I followed were:
- create a new user using sso with ploi
- submit new feature
- asked to check the email (so I lost my content and my new feature was gone, this could be another issue to fix). 
- I created a new feature again. 
- Save it and now it appears on my Items, but not on the Site list, where is supposed to be. 
- I edit it, and the edit works, but I get the error above every time I save it. 

Not sure why it does not appear on the list, maybe it needs to be approved?

**Comment by Cannonb4ll** [comment]
So this is intentional, because the administrators can configure it this way. There's always a way to see your items back by pressing "My items" on the left.

**Comment by angelfplaza** [comment]
Thanks. 
I think this is then an UX bug that would need to be addressed. 
The user is never notified about this and there is no way to see what is going on (unless you open a support ticket).

**Comment by Cannonb4ll** [comment]
To me, it's pretty clear that there's a "My items" link on the left where you see all your submitted items.

**Comment by angelfplaza** [comment]
To me is not clear. 
So at least one person find it confusing.
