### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by ndijkstra** [ploi-deploy/roadmap#64]
It would be nice to keep a change log to show what's new.

**Comment by Cannonb4ll** [comment]
We'll close this, for now, we're using releases with automatic changelog generation for now: https://github.com/ploi-deploy/roadmap/releases

If you feel like, feel free to make an automated process if possible to fill a changelog.md file automatically upon a new release.

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll @ndijkstra Do you mean a change log in the roadmap for projects? If we could tag items to a specific version we could create a changelog indeed. Maybe we need an option to mark items on a specific board as finished / closed

**Comment by ndijkstra** [comment]
Sorry. I had to add a description here. I mean a change log as feature in the roadmap. Where you can create change log items and attach roadmap items to it. And have a page to display all changelog items

**Comment by Cannonb4ll** [comment]
Ok @SebastiaanKloos you were right, I'll buy you a beer.🍺

**Comment by SebastiaanKloos** [comment]
> Ok @SebastiaanKloos you were right, I'll buy you a beer.🍺

You bought me enough Bakker Bart already 😜
